jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: '[Setup] Java'
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: '[Setup] Android'
      uses: android-actions/setup-android@v3
      with:
        cmdline-tools-version: 10406996
        log-accepted-android-sdk-licenses: false
    - continue-on-error: true
      name: '[Test] Linting'
      run: './gradlew ktlintCheck --console=plain

        '
      working-directory: OneSignalSDK
    - continue-on-error: true
      name: '[Test] SDK Unit Tests'
      run: './gradlew testReleaseUnitTest --console=plain --continue

        '
      working-directory: OneSignalSDK
    - continue-on-error: true
      if: failure()
      name: Unit tests results
      uses: actions/upload-artifact@v3
      with:
        name: unit-tests-results
        path: OneSignalSDK/unittest/build
name: Test
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
