jobs:
  calculate:
    if: github.event.issue.pull_request == null
    name: set reponse time for the issue
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      run: npm install @octokit/action@6.0.6
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: set-time
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: 'const os_probot_metadata = require(''./.github/os_probot_metadata.js'')

          const set_response_time = require(''./.github/set_response_times.js'')

          return await set_response_time(context, os_probot_metadata)

          '
    - continue-on-error: true
      name: Get result
      run: echo "${{steps.set-time.outputs.result}}" >> $GITHUB_STEP_SUMMARY
name: Set Response Time
on:
  repository_dispatch:
    types: trigger-ga___set_response_time.yml
