jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
      if: ${{ !github.event.issue.pull_request }}
      name: Call Zapier web hook to close Asana task
      run: "curl --location --request POST 'https://hooks.zapier.com/hooks/catch/12728683/b7009qc/'\
        \ \\\n--header 'Content-Type: application/json' \\\n--header 'Accept: application/json'\
        \ \\\n--data-raw '{\n  \"task_name\" : \"$ISSUE_TITLE\"\n}'\n"
name: Zapier web hook
on:
  repository_dispatch:
    types: trigger-ga___Zapier.yml
permissions:
  issues: read
